### PR TITLE
fixed according to data inspection

### PR DESCRIPTION
**Pull request by c-monkey**
https://oncprojectracking.healthit.gov/support/browse/BONNIE-233

Note, we need up update Bonnie Gemfile.lock after merging this pull request.

### CODE REVIEW

**Comment by c-monkey** [comment]
Fixes these 2 patients:
- denom ex Pass24 NICU Location
- Denom Ex Pass 14 NICUIP

**Comment by edeyoung** [comment]
What's the deal with the `facilityLocation` in `DiagnosticStudy`? This one looks very different. Did it need to be changed?

**Comment by holmesie** [comment]
I missed that one myself, since it's so different. I'm assuming it should also be changed, but I can't find a measure that tests this specific case.

**Comment by c-monkey** [comment]
Looking at: https://github.com/esacinc/clinical_quality_language/blob/master/Src/java/qdm/schema/qdm.5.0.2.draft.11.11.16.xsd
I don't see anything different from `DiagnosticStudy` to the other QDM types with a `facilityLocation`

I'm going to make this code change and then investigate testing it.

**Comment by c-monkey** [comment]
Pull request created: https://github.com/projecttacoma/cql_qdm_patientapi/pull/8

**Pull request merged**
