### PR TITLE
Duplicated 'moment' library from bonnie into cql_qdm_patientapi

### PR DESCRIPTION
**Pull request by c-monkey**
Duplicated 'moment' library from bonnie into cql_qdm_patientapi, but only when running tests
- tweaked test configs to run the most simple cql-dependent test
- removed placeholder example test

This is the first part of replacing https://github.com/projecttacoma/cql_qdm_patientapi/pull/67

JIRA: https://jira.mitre.org/browse/BONNIE-972
TESTS: run 'bundle exec teaspoon'

(in support of Cumulative Medication Duration)

### CODE REVIEW

**Comment by jbradl11** [comment]
Looks good to me. One question, when I run the test why does the output say " 1 example, 0 failures"? Why "example"?

**Comment by c-monkey** [comment]
It does that for the Bonnie teaspoon console runner, too. I poked around for actually almost an hour and never figured out why. In the teaspoon html runner it doesn’t say that. I can’t find “example” in the source code. I figure it's no big deal for now.

**Comment by c-monkey** [comment]
I didn't have instanbul installed, even. But following the 'npm install' request it worked just fine for me. Maybe you need to do a 'bundle install'?

```
Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:57487/teaspoon/default
.

Finished in 0.01300 seconds
1 example, 0 failures

=============================== Coverage summary ===============================
Statements   : 42.93% ( 1138/2651 )
Branches     : 11.43% ( 225/1969 )
Functions    : 26.17% ( 196/749 )
Lines        : 39.69% ( 672/1693 )
================================================================================

```

**Comment by c-monkey** [comment]
I have pushed the config for coverage. This is much cleaner now:

```
=============================== Coverage summary ===============================
Statements   : 42.48% ( 746/1756 )
Branches     : 6.78% ( 53/782 )
Functions    : 30.8% ( 134/435 )
Lines        : 35.97% ( 554/1540 )
================================================================================
```
This doesn't include support libraries.

**Pull request merged**
